### ISSUE TITLE
Crashes on `new MediaDeviceQuery` on Android

### ISSUE THREAD

**Issue by tgrayston** [natmlx/NatDevice#23] opened 2022-11-23 16:04 UTC
Chance of crashing following execution of `new MediaDeviceQuery` on Android. Tested using Google Play's Pre-Launch Report and Android Studio emulators.

Most common crash involves the message `Abort message: 'Scudo ERROR: corrupted chunk header at address...'`

Test Script:
```
namespace NatML.Devices.Tests
{
    using System;
    using System.Collections;
    using UnityEngine;
    using Unity.Collections.LowLevel.Unsafe;
    using System.Threading.Tasks;

    sealed class AudioBufferTest : MonoBehaviour
    {

        private async void Start()
        {
            Application.SetStackTraceLogType(LogType.Log, StackTraceLogType.None);

            await RequestPermissions();

            int reps = 1;

            while (reps < 100)
            {
                Debug.Log($"new MediaDeviceQuery(), attempt {reps}");
                var filter = MediaDeviceCriteria.AudioDevice;
                var query = new MediaDeviceQuery(filter);
                await Task.Delay(1000);
                reps++; // oops missed this line originally so the logs say "attempt 1" repeatedly
            }

        }
        private async Task RequestPermissions()
        {
            PermissionStatus status = MediaDeviceQuery.CheckPermissions<AudioDevice>();
            Debug.Log($"CheckPermissions: {status}");
            if (status != PermissionStatus.Authorized)
            {
                status = await MediaDeviceQuery.RequestPermissions<AudioDevice>();
                Debug.Log($"RequestPermissions: {status}");
            }

        }

    }
}
```

Expected behaviour: no crash.
Experienced behaviour: Crashes usually within about 10 repetitions with various messages on certain devices.
Full logs:
- Pixel 5 API 32 emulator [MediaQueryCrash-Pixel5API32.txt](https://github.com/natmlx/NatDevice/files/10077131/MediaQueryCrash-Pixel5API32.txt)
- Pixel 6 Pro API 33 emulator [MediaQueryCrash-Pixel6ProAPI33.txt](https://github.com/natmlx/NatDevice/files/10077111/MediaQueryCrash-Pixel6ProAPI33.txt)
- Galaxy Nexus API 28 emulator [MediaQueryCrash-GalaxyNexusAPI28.txt](https://github.com/natmlx/NatDevice/files/10077168/MediaQueryCrash-GalaxyNexusAPI28.txt)

**Comment by olokobayusuf** [comment] 2022-12-04 20:09
@tgrayston we've plugged every _potential_ place for this crash to occur. Since it's unreproducible on device (we've gotten no reports of it), I'm closing this issue. It _should_ be fixed in [1.3.2](https://github.com/natmlx/NatDevice/releases/tag/1.3.2).

**Closed by olokobayusuf** 2022-12-04 20:09 UTC
Labels: android, bug, critical
