### ISSUE TITLE
Long hang (30 seconds plus) when starting a device

### ISSUE THREAD

**Issue by nickhudson4** [natmlx/NatDevice#35] opened 2023-04-21 18:19 UTC
It might be similar to this issue https://github.com/natmlx/natdevice/issues/3. 

I am on latest version of NAT. Unity version 2021.3.10f1. The device in question is a Logi 270 HD 

Example code:
```
_output = new TextureOutput();
CurrentDevice.StartRunning(_output);
```

The texture will render gray until the 30 seconds has passed before rendering the cam.

**Comment by olokobayusuf** [comment] 2023-04-24 19:26
Duplicate of natmlx/videokit#47 . Closing.

**Closed as not planned by olokobayusuf** 2023-04-24 19:26 UTC
Labels: duplicate
